# Generated by Django 5.2.6 on 2025-10-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='Editora_id',
            new_name='editora',
        ),
        migrations.RenameField(
            model_name='publica',
            old_name='Autor_id',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='publica',
            old_name='Livro_id',
            new_name='livro',
        ),
    ]
